services:
  munch:
    container_name: munch
    image: jangga/munch
    expose:
      - "3000"
    env_file:
      - ./munch-app/.env
    networks:
      - munch-network
     
  munch-api:
    container_name: munch-api
    image: jangga/munch-api
    expose:
      - "4000"
    env_file:
      - ./munch-api/.env
    depends_on:
      - db
    volumes:
      - ./munch-api:/app
      - ./munch-api/app/static/uploads:/app/app/static/uploads  
    networks:
      - munch-network

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - munch-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - munch-network
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=jacobmondangga@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - munch

volumes:
  postgres_data:
  nginx_secrets:

networks:
  munch-network:
    driver: bridge
