version: '3.8'

services:
  munch-api:
    image: jangga/munch-api
    ports:
      - "4000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - munch-network

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - munch-network

volumes:
  postgres_data:

networks:
  munch-network:
    driver: bridge
